language: php

php:
  - 7.1

sudo: false

services:
  - mysql

env:
  matrix:
    - SHOPWARE_VERSION="5.5"
  global:
    - PLUGIN_NAME=FroshVariantSwitch
    - SHOPWARE_DIRECTORY=${HOME}/shopware
    - PLUGIN_DIRECTORY=${SHOPWARE_DIRECTORY}/custom/plugins

cache:
   directories:
     - ${HOME}/.composer/cache/files

before_script:
  - cd ${TRAVIS_BUILD_DIR}

after_success:
  - ./build.sh
  - wget 'https://github.com/FriendsOfShopware/FroshPluginUploader/blob/master/frosh-plugin-upload.phar?raw=true' -O frosh-plugin-upload.phar
  - php frosh-plugin-upload.phar plugin:upload FroshVariantSwitch*.zip
